---
name: CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        description: "Is a release"
        type: boolean
        default: false
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - "*.go"
      - "**/*.go"
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-fyne-lint.yaml@main
    permissions:
      contents: read
    with:
      cmd: "hack/containerized make lint"

  gosec:
    uses: heathcliff26/ci/.github/workflows/golang-gosec.yaml@main
    permissions:
      contents: read
      security-events: write

  unit-tests:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main
    permissions:
      contents: read
    with:
      cmd: "hack/containerized make test"
      os: ubuntu-latest
      coveralls: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}

  validate:
    uses: heathcliff26/ci/.github/workflows/golang-build.yaml@main
    permissions:
      contents: read
    with:
      cache: false
      cmd: "make validate"

  build:
    uses: heathcliff26/ci/.github/workflows/golang-build.yaml@main
    permissions:
      contents: read
    needs:
      - lint
      - validate
    with:
      artifact: "bin/cultures-trainer"
      artifact-name: "cultures-trainer"
      cmd: "hack/containerized make build"
      release: ${{ inputs.release || false }}
